"""
IaC Exporter - Converts IAM policies to CloudFormation, Terraform, and YAML formats
"""
import json
from typing import Dict, Any, Optional

try:
    import yaml
    YAML_AVAILABLE = True
except ImportError:
    YAML_AVAILABLE = False


def export_to_cloudformation(policy: Dict[str, Any], role_name: Optional[str] = None, trust_policy: Optional[Dict[str, Any]] = None) -> str:
    """
    Convert IAM policy to AWS CloudFormation template
    
    Args:
        policy: IAM policy document
        role_name: Optional role name (if creating a role)
        trust_policy: Optional trust policy (if creating a role)
    
    Returns:
        CloudFormation YAML template as string
    """
    template = {
        'AWSTemplateFormatVersion': '2010-09-09',
        'Description': 'IAM Policy/Role generated by Aegis IAM',
        'Resources': {}
    }
    
    if role_name and trust_policy:
        # Create IAM Role with trust policy
        template['Resources']['IAMRole'] = {
            'Type': 'AWS::IAM::Role',
            'Properties': {
                'RoleName': role_name,
                'AssumeRolePolicyDocument': trust_policy,
                'Policies': [
                    {
                        'PolicyName': f'{role_name}-Policy',
                        'PolicyDocument': policy
                    }
                ]
            }
        }
    else:
        # Create standalone IAM Policy
        policy_name = role_name or 'GeneratedPolicy'
        template['Resources']['IAMPolicy'] = {
            'Type': 'AWS::IAM::Policy',
            'Properties': {
                'PolicyName': f'{policy_name}-Policy',
                'PolicyDocument': policy
            }
        }
    
    # Convert to YAML format
    if not YAML_AVAILABLE:
        raise ImportError("PyYAML is required for CloudFormation export. Install with: pip install PyYAML")
    return yaml.dump(template, default_flow_style=False, sort_keys=False, allow_unicode=True)


def export_to_terraform(policy: Dict[str, Any], role_name: Optional[str] = None, trust_policy: Optional[Dict[str, Any]] = None) -> str:
    """
    Convert IAM policy to Terraform configuration
    
    Args:
        policy: IAM policy document
        role_name: Optional role name (if creating a role)
        trust_policy: Optional trust policy (if creating a role)
    
    Returns:
        Terraform HCL configuration as string
    """
    lines = []
    
    if role_name and trust_policy:
        # Create IAM Role with trust policy
        lines.append(f'resource "aws_iam_role" "{role_name.lower().replace("-", "_")}" {{')
        lines.append(f'  name = "{role_name}"')
        lines.append('')
        lines.append('  assume_role_policy = jsonencode({')
        lines.append('    Version = "2012-10-17"')
        lines.append('    Statement = [')
        
        # Convert trust policy to Terraform format
        for stmt in trust_policy.get('Statement', []):
            lines.append('      {')
            lines.append(f'        Effect = "{stmt.get("Effect", "Allow")}"')
            lines.append('        Principal = {')
            
            principal = stmt.get('Principal', {})
            if isinstance(principal, dict):
                for key, value in principal.items():
                    if isinstance(value, list):
                        lines.append(f'          {key} = {json.dumps(value)}')
                    else:
                        lines.append(f'          {key} = "{value}"')
            
            lines.append('        }')
            
            if 'Action' in stmt:
                action = stmt['Action']
                if isinstance(action, list):
                    lines.append(f'        Action = {json.dumps(action)}')
                else:
                    lines.append(f'        Action = "{action}"')
            
            if 'Condition' in stmt:
                lines.append('        Condition = {')
                for cond_key, cond_value in stmt['Condition'].items():
                    lines.append(f'          {cond_key} = {json.dumps(cond_value)}')
                lines.append('        }')
            
            lines.append('      },')
        
        lines.append('    ]')
        lines.append('  })')
        lines.append('}')
        lines.append('')
        
        # Attach inline policy
        lines.append(f'resource "aws_iam_role_policy" "{role_name.lower().replace("-", "_")}_policy" {{')
        lines.append(f'  name = "{role_name}-Policy"')
        lines.append(f'  role = aws_iam_role.{role_name.lower().replace("-", "_")}.id')
        lines.append('')
        lines.append('  policy = jsonencode(')
        lines.append(json.dumps(policy, indent=4))
        lines.append('  )')
        lines.append('}')
    else:
        # Create standalone IAM Policy
        policy_name = role_name or 'generated_policy'
        lines.append(f'resource "aws_iam_policy" "{policy_name.lower().replace("-", "_")}" {{')
        lines.append(f'  name        = "{policy_name}"')
        lines.append(f'  description = "IAM policy generated by Aegis IAM"')
        lines.append('')
        lines.append('  policy = jsonencode(')
        lines.append(json.dumps(policy, indent=4))
        lines.append('  )')
        lines.append('}')
    
    return '\n'.join(lines)


def export_to_yaml(policy: Dict[str, Any], role_name: Optional[str] = None, trust_policy: Optional[Dict[str, Any]] = None) -> str:
    """
    Convert IAM policy to YAML format (for Kubernetes, Ansible, etc.)
    
    Args:
        policy: IAM policy document
        role_name: Optional role name
        trust_policy: Optional trust policy
    
    Returns:
        YAML formatted policy as string
    """
    if not YAML_AVAILABLE:
        raise ImportError("PyYAML is required for YAML export. Install with: pip install PyYAML")
    
    output = {
        'iam_policy': {
            'name': role_name or 'GeneratedPolicy',
            'policy_document': policy
        }
    }
    
    if trust_policy:
        output['iam_policy']['trust_policy'] = trust_policy
    
    return yaml.dump(output, default_flow_style=False, sort_keys=False, allow_unicode=True)


def get_export_formats() -> Dict[str, str]:
    """
    Get available export formats
    
    Returns:
        Dictionary mapping format names to descriptions
    """
    return {
        'cloudformation': 'AWS CloudFormation Template (YAML)',
        'terraform': 'Terraform Configuration (HCL)',
        'yaml': 'YAML Format (Generic)',
        'json': 'JSON Format (Original)'
    }

