/**
 * Utility functions for generating and downloading email reports
 */

export interface ReportData {
  title: string;
  generatedDate: string;
  score?: number;
  scoreLabel?: string;
  findings?: Array<{
    severity: string;
    title: string;
    description?: string;
    recommendation?: string;
  }>;
  summary?: string;
  quickWins?: string[];
  recommendations?: string[];
  [key: string]: any;
}

/**
 * Generates a formatted text report
 */
export const generateTextReport = (data: ReportData): string => {
  const lines: string[] = [];
  
  lines.push('='.repeat(60));
  lines.push(data.title.toUpperCase());
  lines.push('='.repeat(60));
  lines.push('');
  lines.push(`Generated: ${data.generatedDate}`);
  lines.push('');
  
  if (data.score !== undefined) {
    lines.push(`Security Score: ${data.score}/100${data.scoreLabel ? ` (${data.scoreLabel})` : ''}`);
    lines.push('');
  }
  
  if (data.findings && data.findings.length > 0) {
    const severityCounts = data.findings.reduce((acc, f) => {
      acc[f.severity] = (acc[f.severity] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);
    
    lines.push('FINDINGS SUMMARY:');
    lines.push(`- Critical: ${severityCounts['Critical'] || 0}`);
    lines.push(`- High: ${severityCounts['High'] || 0}`);
    lines.push(`- Medium: ${severityCounts['Medium'] || 0}`);
    lines.push(`- Low: ${severityCounts['Low'] || 0}`);
    lines.push('');
    
    lines.push('DETAILED FINDINGS:');
    data.findings.forEach((finding, index) => {
      lines.push('');
      lines.push(`${index + 1}. [${finding.severity}] ${finding.title}`);
      if (finding.description) {
        lines.push(`   Description: ${finding.description}`);
      }
      if (finding.recommendation) {
        lines.push(`   Recommendation: ${finding.recommendation}`);
      }
    });
    lines.push('');
  }
  
  if (data.quickWins && data.quickWins.length > 0) {
    lines.push('QUICK WINS:');
    data.quickWins.forEach((win, index) => {
      lines.push(`${index + 1}. ${win}`);
    });
    lines.push('');
  }
  
  if (data.recommendations && data.recommendations.length > 0) {
    lines.push('RECOMMENDATIONS:');
    data.recommendations.forEach((rec, index) => {
      lines.push(`${index + 1}. ${rec}`);
    });
    lines.push('');
  }
  
  if (data.summary) {
    lines.push('SUMMARY:');
    lines.push(data.summary);
    lines.push('');
  }
  
  lines.push('='.repeat(60));
  lines.push('Report generated by Aegis IAM');
  lines.push('='.repeat(60));
  
  return lines.join('\n');
};

/**
 * Generates a JSON report
 */
export const generateJSONReport = (data: ReportData): string => {
  return JSON.stringify(data, null, 2);
};

/**
 * Downloads a file with the given content
 */
export const downloadFile = (content: string, filename: string, mimeType: string = 'text/plain'): void => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Downloads report file and opens email client with instructions
 * Note: mailto: links cannot attach files, so we download the file
 * and provide instructions in the email body
 */
export const emailReport = (data: ReportData, format: 'text' | 'json' = 'text'): void => {
  const reportContent = format === 'json' 
    ? generateJSONReport(data) 
    : generateTextReport(data);
  
  const extension = format === 'json' ? 'json' : 'txt';
  const filename = `aegis-iam-report-${new Date().toISOString().split('T')[0]}.${extension}`;
  
  // Create email body with summary and attachment instructions
  const emailBody = [
    data.title,
    '',
    `Generated: ${data.generatedDate}`,
    '',
    'Please find the detailed security report attached to this email.',
    '',
    '📎 ATTACHMENT INSTRUCTIONS:',
    `The report file "${filename}" will be downloaded to your Downloads folder.`,
    'Please attach it to this email before sending:',
    '1. Click the paperclip icon (📎) in your email client',
    `2. Navigate to your Downloads folder`,
    `3. Select the file: ${filename}`,
    '',
    '---',
    '',
    'Brief Summary:',
    ...(data.score !== undefined ? [`Security Score: ${data.score}/100${data.scoreLabel ? ` (${data.scoreLabel})` : ''}`] : []),
    ...(data.findings && data.findings.length > 0 
      ? [`Total Findings: ${data.findings.length}`,
         `- Critical: ${data.findings.filter(f => f.severity === 'Critical').length}`,
         `- High: ${data.findings.filter(f => f.severity === 'High').length}`,
         `- Medium: ${data.findings.filter(f => f.severity === 'Medium').length}`,
         `- Low: ${data.findings.filter(f => f.severity === 'Low').length}`] 
      : []),
    '',
    'Report generated by Aegis IAM - AI-Powered AWS IAM Security',
    'For more information, visit: https://github.com/bhavikam28/aegis-iam'
  ].join('\n');
  
  // Prepare mailto link
  const subject = encodeURIComponent(data.title);
  const body = encodeURIComponent(emailBody);
  const mailto = `mailto:?subject=${subject}&body=${body}`;
  
  // Function to open email client
  const openEmailClient = () => {
    // Try multiple methods to ensure email client opens
    try {
      // Method 1: Create and click a link (most reliable)
      const link = document.createElement('a');
      link.href = mailto;
      link.target = '_blank';
      link.style.display = 'none';
      document.body.appendChild(link);
      link.click();
      
      // Clean up after a short delay
      setTimeout(() => {
        if (document.body.contains(link)) {
          document.body.removeChild(link);
        }
      }, 100);
    } catch (e) {
      console.warn('Link method failed, trying window.open:', e);
      // Method 2: Use window.open
      try {
        window.open(mailto, '_blank');
      } catch (e2) {
        console.warn('window.open failed, trying location.href:', e2);
        // Method 3: Direct navigation (last resort)
        try {
          window.location.href = mailto;
        } catch (e3) {
          console.error('All email opening methods failed:', e3);
          // Show alert as last resort
          alert(`Unable to open email client automatically.\n\nPlease:\n1. Open your email client manually\n2. The report file "${filename}" will be downloaded\n3. Attach the file from your Downloads folder`);
        }
      }
    }
  };
  
  // Try Web Share API first (mobile) - this DOES support file attachments
  if (navigator.share && navigator.canShare) {
    try {
      const file = new File([reportContent], filename, { 
        type: format === 'json' ? 'application/json' : 'text/plain' 
      });
      
      // Check if we can share files
      if (navigator.canShare({ files: [file] })) {
        navigator.share({
          title: data.title,
          text: emailBody,
          files: [file]
        }).catch((error) => {
          console.log('Web Share API failed, falling back to mailto:', error);
          // Fallback: open email and download file
          openEmailClient();
          setTimeout(() => {
            downloadFile(reportContent, filename, format === 'json' ? 'application/json' : 'text/plain');
          }, 300);
        });
        return;
      }
    } catch (error) {
      console.log('Web Share API not available, using mailto:', error);
    }
  }
  
  // Desktop: Open email client FIRST, then trigger download
  // This prevents the download dialog from blocking the email client
  openEmailClient();
  
  // Then trigger download after a short delay
  setTimeout(() => {
    downloadFile(reportContent, filename, format === 'json' ? 'application/json' : 'text/plain');
  }, 300);
};

